import { config } from "./config.js";
import { createLogger } from "./logger.js";
import type { TaskInfo } from "./jira.js";
import type { ClaudeResult } from "./claude.js";
import * as slackBot from "./slack-bot.js";

const log = createLogger();

interface SlackTextObj {
  type: string;
  text: string;
}

interface SlackBlock {
  type: string;
  text?: SlackTextObj;
  elements?: Array<{ type: string; text?: string | SlackTextObj; url?: string }>;
  fields?: Array<SlackTextObj>;
}

export async function notifySuccess(
  task: TaskInfo,
  result: ClaudeResult,
): Promise<{ ts: string; channel: string } | void> {
  const blocks: SlackBlock[] = [
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*AI implementation complete: <${task.url}|${task.key}>*\n${task.summary}`,
      },
    },
    {
      type: "section",
      fields: [
        { type: "mrkdwn", text: `*PR:*\n<${result.prUrl}|View Pull Request>` },
        { type: "mrkdwn", text: `*Duration:*\n${(result.durationMs / 1000).toFixed(0)}s` },
      ],
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `Auto-generated by Claude Code. Reply in this thread to provide feedback.`,
        },
      ],
    },
  ];

  if (slackBot.isActive() && config.slack.channel) {
    return slackBot.postMessage(config.slack.channel, blocks);
  }

  if (config.slack.webhookUrl) {
    await sendSlack({ blocks });
  }
}

export async function notifyFailure(
  task: TaskInfo,
  error: string,
): Promise<{ ts: string; channel: string } | void> {
  const blocks: SlackBlock[] = [
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*AI implementation failed: <${task.url}|${task.key}>*\n${task.summary}`,
      },
    },
    {
      type: "section",
      text: {
        type: "mrkdwn",
        text: `\`\`\`${error.slice(0, 500)}\`\`\``,
      },
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: "Manual intervention required. Reply in this thread to provide feedback.",
        },
      ],
    },
  ];

  if (slackBot.isActive() && config.slack.channel) {
    return slackBot.postMessage(config.slack.channel, blocks);
  }

  if (config.slack.webhookUrl) {
    await sendSlack({ blocks });
  }
}

export async function notifyWorkerStart(): Promise<void> {
  const text = `JIRA AI Worker started. Polling every ${config.worker.pollIntervalMs / 60000} min for \`${config.jira.triggerLabel}\` tasks in ${config.jira.project}.`;

  if (slackBot.isActive() && config.slack.channel) {
    await slackBot.postMessage(config.slack.channel, [
      { type: "section", text: { type: "mrkdwn", text } },
    ]);
    return;
  }

  if (config.slack.webhookUrl) {
    await sendSlack({ text });
  }
}

export async function notifyTaskStarted(
  task: TaskInfo,
): Promise<{ ts: string; channel: string } | void> {
  if (!slackBot.isActive() || !config.slack.channel) return;

  try {
    const mainBlocks: SlackBlock[] = [
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*🔧 ${task.key}: ${task.summary}*\nPriority: ${task.priority} · Type: ${task.issueType}`,
        },
      },
    ];

    const threadInfo = await slackBot.postMessage(config.slack.channel, mainBlocks);

    // Post JIRA link in thread immediately
    await slackBot.replyInThread(
      threadInfo.channel,
      threadInfo.ts,
      `📋 JIRA: <${task.url}|${task.key}>`,
    );

    return threadInfo;
  } catch (err) {
    log.warn(`Slack Bolt notification failed, falling back to webhook mode: ${err}`);
    return undefined;
  }
}

export async function notifyTaskStatus(
  channel: string | undefined,
  threadTs: string | undefined,
  text: string,
): Promise<void> {
  if (!channel || !threadTs || !slackBot.isActive()) return;

  try {
    await slackBot.replyInThread(channel, threadTs, text);
  } catch (err) {
    log.warn(`Slack thread status update failed: ${err}`);
  }
}

export async function notifyTaskCompleted(
  task: TaskInfo,
  result: ClaudeResult,
  channel: string | undefined,
  threadTs: string | undefined,
): Promise<{ ts: string; channel: string } | void> {
  // Bolt thread mode
  if (channel && threadTs && slackBot.isActive()) {
    try {
      // Post success in thread
      await slackBot.replyInThread(
        channel,
        threadTs,
        `✅ PR created: <${result.prUrl}|View Pull Request>\nDuration: ${(result.durationMs / 1000).toFixed(0)}s`,
      );

      // Update main message
      await slackBot.updateMessage(channel, threadTs, [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*✅ ${task.key}: ${task.summary} — Done*\nPriority: ${task.priority} · Type: ${task.issueType}`,
          },
        },
      ], `${task.key}: ${task.summary} — Done`);

      return { ts: threadTs, channel };
    } catch (err) {
      log.warn(`Slack Bolt completion notification failed, falling back to webhook: ${err}`);
    }
  }

  // Webhook fallback
  return notifySuccess(task, result);
}

export async function notifyTaskFailed(
  task: TaskInfo,
  error: string,
  channel: string | undefined,
  threadTs: string | undefined,
): Promise<{ ts: string; channel: string } | void> {
  // Bolt thread mode
  if (channel && threadTs && slackBot.isActive()) {
    try {
      // Post failure in thread
      await slackBot.replyInThread(
        channel,
        threadTs,
        `❌ Implementation failed:\n\`\`\`${error.slice(0, 500)}\`\`\``,
      );

      // Update main message
      await slackBot.updateMessage(channel, threadTs, [
        {
          type: "section",
          text: {
            type: "mrkdwn",
            text: `*❌ ${task.key}: ${task.summary} — Failed*\nPriority: ${task.priority} · Type: ${task.issueType}`,
          },
        },
      ], `${task.key}: ${task.summary} — Failed`);

      return { ts: threadTs, channel };
    } catch (err) {
      log.warn(`Slack Bolt failure notification failed, falling back to webhook: ${err}`);
    }
  }

  // Webhook fallback
  return notifyFailure(task, error);
}

async function sendSlack(payload: Record<string, unknown>): Promise<void> {
  try {
    const response = await fetch(config.slack.webhookUrl, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      log.warn(`Slack webhook returned ${response.status}`);
    }
  } catch (err) {
    log.warn(`Slack notification failed: ${err}`);
  }
}
